# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "zh-TW"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - k1dav/pdf-image-combine

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Dave Sung's Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "Dave Sung"

# Tagline section text
tagline: >-
  AI R&D Team Lead | Bridging AI research & product. Background in AI, backend & databases. Building standardized model training pipelines and guiding full-cycle AI projects. Recently exploring vibe coding to drive multiple projects in parallel.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-github"
      text: "GitHub Profile"
      url: "https://github.com/k1dav"
      alt: "Dave Sung's GitHub Profile"
      title: "Dave Sung's GitHub Profile"
      target: "_blank"
  - link:
      icon: "fa-solid fa-file-pdf"
      text: "PDF 圖片合併工具"
      url: "https://k1dav.github.io/pdf-image-combine/"
      alt: "PDF 圖片合併工具 - 線上將 PDF 和圖片合併"
      title: "PDF 圖片合併工具 - 線上將 PDF 和圖片合併"
      target: "_blank"
  - link:
      icon: "fa-brands fa-linkedin"
      text: "LinkedIn Profile"
      url: "https://www.linkedin.com/in/sung-feng/"
      alt: "Dave Sung's LinkedIn Profile"
      title: "Dave Sung's LinkedIn Profile"
      target: "_blank"

# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/k1dav"
      title: "Dave Sung's GitHub"
      alt: "Dave Sung's GitHub"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/sung-feng/"
      title: "Dave Sung's LinkedIn"
      alt: "Dave Sung's LinkedIn"
      target: "_blank"
  - social:
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/k1dave6412"
      title: "Dave Sung's Facebook"
      alt: "Dave Sung's Facebook"
      target: "_blank"

# Footer text
footer: >
  你好！歡迎來到我的連結頁面。可以在 GitHub 上找到我的專案，或在 LinkedIn 和 Facebook 上與我聯繫。

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://github.com/k1dav" target="_blank">Dave Sung</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
